apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: go-web-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/mayurjadhav-23/go-web-app.git
    targetRevision: HEAD
    path: helm/go-web-app-chart  # ✅ uses your Helm chart directory
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
